### ISSUE TITLE
didFinish method never called when task is finished

### ISSUE THREAD

**Issue by pimeo** [arikis/Overdrive#15]
**Overdrive:** `0.2.2`
**Package manager (SPM, Carthage, CocoaPods, Manual):** `CocoaPods`
**Xcode:** `8.0`
**Platform:** `iOS 10.0`

Hi,

Following your [test class](https://github.com/arikis/Overdrive/blob/master/Tests/OverdriveTests/TaskQueueDelegateTests.swift), I wrote a basic example:  

```swift
// Custom Task
class ImageTask: Task<UIImage> {
    
    override func run() {

        let logoURL = URL(string: "http://i2.cdn.cnn.com/cnnnext/dam/assets/161217142430-2017-cars-ferrari-1-exlarge-169.jpg")!
        
        do {
            let logoData = try Data(contentsOf: logoURL)
            let image = UIImage(data: logoData)!
            finish(with: .value(image)) // finish with image
            
        } catch {
            finish(with: .error(error)) // finish with error if any
        }
    }
    
}

// Custom Task Queue
class CustomTaskQueue: TaskQueueDelegate {
    private var queue:TaskQueue
    
    public init() {
        self.queue = TaskQueue(qos: .default)
        self.queue.delegate = self
    }
    
    public func start() {
        let t1 = ImageTask()
        t1.name = "Image Task"
        t1.onValue { image in
            print("image downloaded \(image)")
        }
        
        t1.onError { error in
            print("image error \(error.localizedDescription)")
        }
        
        self.queue.add(task: t1)
    }
    
    func didAdd<T>(task: Task<T>, toQueue queue: TaskQueue) {
        print("task did add \(task.name)")
    }
    
    func didFinish<T>(task: Task<T>, inQueue queue: TaskQueue) {
        print("task did finish \(task.name)")
    }
    
}
```

And then call it via the following lines: 

```swift
let taskQueue = CustomTaskQueue()
taskQueue.start()
```

The Xcode terminal log output: 

```
task did add Optional("Image Task")
image downloaded <UIImage: 0x61800008f0a0>, {780, 438}
```

I can't receive the end message `task did finish Optional("Image Task")` when a task has been finished. I listen to the `didFinish<T>(task: Task<T>, inQueue queue: TaskQueue)` method but nothing happens. Did I make a mistake ? 

Thank you in advance

**Comment by arikis** [comment]
The problem is that your `queue` instance is deallocated before the `didFinish(task:inQueue)` is called. For example, imagine if you had this method:

```swift
func doSomething() {
  let queue = CustomTaskQueue()
  queue.start()
}
```

After the `start()` method is executed, `doSomething()` method will return and deallocate the `queue` instance. However, task execution is asynchronous, and by the time it finishes, `queue` instance may be deallocated. That means that the `didFinish(task:inQueue)` method is never called.

Also, this specific code is structured this way because of how `XCTest` cases are structured, and you shouldn't use the same principle in your code. Most of the time `TaskQueueDelegate` should never know anything about the underlying queue. So, you implement `TaskQueueDelegate`methods in some class and add it to existing `TaskQueue`

```swift
class SomeTaskQueueDelegate {
 // Implement methods
}

let queue = TaskQueue(qos: .default)
let delegate = SomeTaskQueueDelegate()

queue.delegate = delegate

let task = ImageTask()
queue.add(task: task)
```

Still, you'll need to make sure that you don't loose reference to your `TaskQueue` instances (like you would do for any other object).

Hope that this was helpful.

**Comment by pimeo** [comment]
Thank you @arikis for the detailed precisions. It's logic now. My mistake was to do not consider observers  in my tests to get information when a task begins and finishes.
